[phases.setup]
nixPkgs = ['maven', 'temurin-bin-17']

[phases.build]
cmds = [
    'mvn clean package -DskipTests -B',
    'mv target/midjourney-proxy-*.jar app.jar'
]

[phases.start]
cmd = 'java $JAVA_OPTS -jar app.jar'

[variables]
JAVA_OPTS = '-XX:MaxRAMPercentage=75 -Djava.awt.headless=true -XX:+UseG1GC -XX:+UseStringDeduplication -Dserver.port=$PORT -Duser.timezone=UTC -Dspring.profiles.active=railway'
